### PR TITLE
Request for full membership

### PR DESCRIPTION
**Pull request by clehner**
I would like to be considered a full member of SSBC, as I have...

- participated in meetings for a length of time
- contributed substantially to the SSB software ecosystem
- met a current member (@pfraze) in person

and am committed to working with the members to further the goals of the group.

### CODE REVIEW

**Comment by pfraze** [comment]
I'm 👍  this!

**Comment by dominictarr** [comment]
absolutely. I had been thinking this felt sillier and sillier. full member definitely

**Comment by pfraze** [comment]
merged!

**Comment by clehner** [comment]
thanks all

**Pull request merged**
